# Generated by Django 3.1.6 on 2021-02-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceRoom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rooms',
            name='projector',
            field=models.BooleanField(default=True),
        ),
    ]
