# Generated by Django 3.1.6 on 2021-02-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceRoom', '0002_auto_20210204_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='projector',
            field=models.BooleanField(default=False),
        ),
    ]
