# Generated by Django 3.1.6 on 2021-02-06 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceRoom', '0003_auto_20210204_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=256)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConferenceRoom.rooms')),
            ],
            options={
                'unique_together': {('date', 'room_id')},
            },
        ),
    ]
