# Generated by Django 3.1.6 on 2021-02-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceRoom', '0004_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room_id',
            new_name='rooms',
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('date', 'rooms')},
        ),
    ]
